name: Test

on:
  push:
    branches: [ xgboost ]
  pull_request:
    branches: [ xgboost ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: bazel test //tensorflow_serving/...
